language: node_js
node_js:
- 6.4.0
addons:
  apt:
    packages:
      - oracle-java8-set-default
script:
- npm test
- java -version
- npm run setup-selenium
- npm run example &
- npm run e2e
deploy:
  provider: npm
  email: justinjmccandless@gmail.com
  api_key:
    secure: cQQ7nxbqZEPBjd8iRLh8gQGTW9Ueh/c2MU/pVkJsaCA3aM90kJF/ekAJI0NAeipsT1vEXPs554vMK8KjTgNCbrklf8hdxj36sMmJPWR8/+yXdsSrPXCLurpemjhAQCtIdFteB13k62OREE8QD9IwQjqKRH63UJH8pIjmAN5VJe6t9mpaNP8lQfR+CTJvfgNLJcWuabFF3tXJ4BJB0aJYfeUPT86qoTY2vQPtPKOTC1urZx/+u4O0vawKYCJizxk5+NAVDndvBh5q0qf98OKeceRs7tdvhuQsCeN0OsM93oqbOsJ+sfO1xIuQ3aRbd+xWF3GE6kJH9mMryZ6uD+K+EwM12AoaFMFrPoV1RycnzHmN3cXr2BeFbVza4DTHCubfF0yRf2277ykOyTnXGcAy0ntKy+pj/V5Ftrl7pCikDEXBhppohEp/vaWaGUCPb6VhU4T5W5kdwt4GAD01D5q5LPJgIkxfjqzixixrIw0CkmNb7vOdKnuQoadC4i7YCf3MeMZnEqgB2EJTlCezQL7qZVJhRYNRL0uPaQ7g7WH30C77lhr3FfJc2q7gOVulv1XbZkHh2YF2hSTE/FuV4cgM/7tl8xABppKOqxuRk8DH7oXv6iFan+XzCKQkV6TcnWd1TweJPOiJhkF8S24RbUgAQDrPHsr76fBEntepfvZonLY=
  skip_cleanup: true
  on:
    tags: true
    repo: Autodesk/molecule-3d-for-react
