language: node_js
node_js:
- 6.4.0
addons:
  apt:
    packages:
      - oracle-java8-set-default
script:
- npm test
- java -version
- npm run setup-selenium
- npm run example &
- npm run e2e
deploy:
  provider: npm
  email: justinjmccandless@gmail.com
  api_key:
    secure: FoIe2m948Jie1ON8CIKMlpBHoQTaXEqw0/80tx6KkksLindeVuA+0gp72GVg86MvxoOL2taice4qaQtHinfCI3XlHvYbkiw4Zg2wBANMXbBvxftk8kocBG3PPu93xvNP3aYfB8nmKC+T+apA5nN9lZTpQI+HtYNNJTo8I5d/18ReIh5VN+0YmilNbzu3Ogf3S8P3uOYySFyQLQKSzOVjsDCEvlFnPoD5mUXuDJbqntmEqrwTwC8+aRVf0FbkmIeHdJx/lfzMO9/c390UMzvV1BvJ1ywgFvqahtRIXmSgdsHZoKR+OYPKxUuvYAHuvs3Wzvf4CayQ67aaDXxTsBkDxBdiqIqBzt8LUMVsHny6m+g5A8RJ0IAL58TqAataxtbkVYjzVH81qa8lG1uzdbpfsacmu/AAi4t9rpDp61FLnav0czY9siGN6pmWHKC5fs4Z2XKgyE8NX9TSZ9nQTj57Fje5ykzOcoRrb0u4qIaCMzx0LyZCx0hK0oJgPbSpPgiW35WoB4g9Gplw8HI8qVTAvlzSjwPSqJt7BPFANDS6YZ4HUAe1QM1+rU64BQBgfXEkwc1BJCjVd2HcBnnOBYQpehTW6qLy4sWM3jtUqegovnqykegkDBVPfv9FGc8H+KJtPNd5aUtTGX4hUmcPFYDxMstzx9p/NG4/SVyApjPC8SY=
  on:
    tags: true
    repo: Autodesk/molecule-3d-for-react
