export default [
  { visualization_type: 'stick', color: '#fedcba' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#fedcba' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#abcdef' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
  { visualization_type: 'stick', color: '#bada55' },
];
